@startuml
'https://plantuml.com/class-diagram

interface Handler {
    +HandleRequest()
}
hide Handler fields

Class Client
hide Client members

class ConcreteHandler1 {
}
hide ConcreteHandler1 members

class ConcreteHandler2 {
}
hide ConcreteHandler2 members

Client -> Handler

ConcreteHandler1 --|> Handler
ConcreteHandler2 --|> Handler

Handler -> Handler :successor

@enduml